Add support for more method types and other improvements
metglobal-compass/core-api-java-client pull request #14
Opened 2020-09-16 05:44 UTC by EmreKp

- Support for more REST methods
- Standatdize writable method (change ile başlamasını düşündüm, önerilere açığım)
- Add method info on request-response log

2020-09-18 11:10 UTC, goksagun approved these changes

2020-10-08 13:22 UTC, MehGokalp requested changes

2020-10-08 13:22 UTC, MehGokalp commented on src/main/java/compass_api/client/CompassClient.java
> +    // TODO: Remove this.
Remove, but why?

2020-10-08 13:25 UTC, EmreKp commented on src/main/java/compass_api/client/CompassClient.java
> +    // TODO: Remove this.
ii dedin gıral, onu da belirtiyim.

2020-10-14 14:25 UTC, MehGokalp approved these changes

2020-10-15 06:45 UTC, merged